import { Download, File, FilePlus2, Folder, FolderPlus, Grid2X2, Heart, List, MoreVertical, RefreshCw, Search, Upload, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { api, baixar, enviarArquivo, ErroApi } from '../api/cliente';
import { Carregando, Chip, ErroEstado, Modal, Paginacao, Vazio } from '../componentes/Comuns';
import { useAviso } from '../contexto/AvisoContexto';
import type { Documento, Pagina, Pasta } from '../types';
import { formatarBytes, formatarData, rotulo } from '../utils';

type Conteudo = { pasta: Pasta; caminho: Array<{ id: string; nome: string }>; subpastas: Pasta[]; documentos: Pagina<Documento> };

export function Arquivos() {
  const [busca] = useSearchParams(); const navegar = useNavigate(); const avisar = useAviso();
  const pastaId = busca.get('pasta'); const [dados, setDados] = useState<Conteudo | null>(null); const [raizes, setRaizes] = useState<Pasta[]>([]);
  const [carregando, setCarregando] = useState(true); const [erro, setErro] = useState(''); const [pagina, setPagina] = useState(1);
  const [grade, setGrade] = useState(localStorage.getItem('govdoc.exibicao') !== 'lista'); const [termo, setTermo] = useState('');
  const [novaPasta, setNovaPasta] = useState(false); const [upload, setUpload] = useState(false); const [chave, setChave] = useState(0);

  useEffect(() => { if (busca.get('enviar') === '1') setUpload(true); }, [busca]);
  useEffect(() => {
    setCarregando(true); setErro('');
    const pedido = pastaId ? api.get<Conteudo>(`/pastas/${pastaId}/conteudo?pagina=${pagina}&por_pagina=50`) : api.get<Pasta[]>('/pastas');
    pedido.then((res) => { if (Array.isArray(res)) { setRaizes(res); setDados(null); } else setDados(res); }).catch((e) => setErro(e instanceof ErroApi ? e.message : 'Falha ao carregar os arquivos.')).finally(() => setCarregando(false));
  }, [pastaId, pagina, chave]);

  const pastas = (dados?.subpastas || raizes).filter((p) => p.nome.toLowerCase().includes(termo.toLowerCase()));
  const documentos = (dados?.documentos.itens || []).filter((d) => d.nome_exibicao.toLowerCase().includes(termo.toLowerCase()));
  function atualizar() { setChave((v) => v + 1); }
  async function favorito(tipo: 'pastas' | 'documentos', id: string) { try { await api.post(`/${tipo}/${id}/favorito`); atualizar(); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha ao favoritar.', 'erro'); } }

  if (carregando) return <Carregando texto="Abrindo o acervo…"/>;
  if (erro) return <ErroEstado mensagem={erro} tentar={atualizar}/>;
  return <>
    <div className="cabecalho-pagina"><div><div className="trilha"><Link to="/arquivos">Meus arquivos</Link>{dados?.caminho.map((item) => <span key={item.id}>› <Link to={`/arquivos?pasta=${item.id}`}>{item.nome}</Link></span>)}</div><h1>{dados?.pasta.nome || 'Meus arquivos'}</h1><p className="subtitulo">{dados?.pasta.descricao || 'Organize, consulte e compartilhe o acervo institucional.'}</p></div>
      <div className="barra-acoes"><button className="botao" onClick={() => setNovaPasta(true)}><FolderPlus size={17}/> Nova pasta</button><button className="botao principal" onClick={() => setUpload(true)} disabled={!pastaId}><Upload size={17}/> Enviar documento</button></div></div>
    {!pastaId && upload && <div className="aviso atencao"><Folder size={20}/><div className="texto"><div className="titulo">Escolha uma pasta de destino</div>Abra uma das pastas abaixo e então envie o documento.</div><button className="botao pequeno" onClick={() => setUpload(false)}>Entendi</button></div>}
    <div className="barra-explorador"><div className="filtro-busca"><Search size={17}/><input type="search" value={termo} onChange={(e) => setTermo(e.target.value)} placeholder="Filtrar esta pasta…"/></div><span className="texto-secundario">{pastas.length} pasta(s) · {documentos.length} documento(s)</span><button className="botao sutil icone" title="Atualizar" onClick={atualizar}><RefreshCw size={17}/></button><div className="alternador"><button className={grade ? 'ativo' : ''} onClick={() => { setGrade(true); localStorage.setItem('govdoc.exibicao', 'grade'); }} aria-label="Exibir em grade"><Grid2X2 size={17}/></button><button className={!grade ? 'ativo' : ''} onClick={() => { setGrade(false); localStorage.setItem('govdoc.exibicao', 'lista'); }} aria-label="Exibir em lista"><List size={18}/></button></div></div>
    {!pastas.length && !documentos.length ? <Vazio titulo={termo ? 'Nenhum item corresponde ao filtro' : 'Esta pasta está vazia'} texto={termo ? 'Tente usar outro termo.' : 'Crie uma subpasta ou envie o primeiro documento.'} acao={!termo && pastaId ? <button className="botao principal" onClick={() => setUpload(true)}><Upload size={17}/> Enviar documento</button> : undefined}/> : grade ?
      <div className="grade-arquivos">{pastas.map((p) => <article className="cartao-arquivo" key={p.id}><Link className="arquivo-link" to={`/arquivos?pasta=${p.id}`}><Folder className="icone-pasta" fill={p.cor || '#2563eb'} size={38}/><span className="nome">{p.nome}</span><span className="meta">{p.total_subpastas} pastas · {p.total_documentos} arquivos</span></Link><button className="acao-canto" aria-label="Favoritar pasta" onClick={() => favorito('pastas', p.id)}><Heart size={16} fill={p.favorito ? 'currentColor' : 'none'}/></button></article>)}
      {documentos.map((d) => <article className="cartao-arquivo" key={d.id}><Link className="arquivo-link" to={`/documentos/${d.id}`}><File className="icone-arquivo" size={36}/><span className="nome">{d.nome_exibicao}</span><span className="meta">{d.extensao?.toUpperCase()} · {formatarBytes(d.tamanho_bytes)}</span><Chip cor={d.classificacao === 'publico' ? 'verde' : d.classificacao === 'interno' ? 'azul' : 'amarelo'}>{rotulo(d.classificacao)}</Chip></Link><button className="acao-canto" aria-label="Favoritar documento" onClick={() => favorito('documentos', d.id)}><Heart size={16} fill={d.favorito ? 'currentColor' : 'none'}/></button></article>)}</div> :
      <div className="tabela-rolagem"><table className="tabela"><thead><tr><th>Nome</th><th>Classificação</th><th>Responsável</th><th>Atualização</th><th>Tamanho</th><th><span className="somente-leitores">Ações</span></th></tr></thead><tbody>{pastas.map((p) => <tr key={p.id}><td><div className="celula-principal"><Folder className="icone-pasta" size={22}/><Link className="nome" to={`/arquivos?pasta=${p.id}`}>{p.nome}</Link></div></td><td><Chip cor="azul">{rotulo(p.classificacao)}</Chip></td><td>{p.responsavel_nome || '—'}</td><td>{formatarData(p.atualizado_em)}</td><td>—</td><td><button className="botao sutil icone" onClick={() => favorito('pastas', p.id)}><Heart size={17} fill={p.favorito ? 'currentColor' : 'none'}/></button></td></tr>)}{documentos.map((d) => <tr key={d.id}><td><div className="celula-principal"><File size={21}/><div><Link className="nome" to={`/documentos/${d.id}`}>{d.nome_exibicao}</Link><div className="celula-secundaria">{d.codigo} · v{d.versao_atual}</div></div></div></td><td><Chip>{rotulo(d.classificacao)}</Chip></td><td>{d.responsavel_nome || '—'}</td><td>{formatarData(d.atualizado_em)}</td><td>{formatarBytes(d.tamanho_bytes)}</td><td><button className="botao sutil icone" onClick={() => baixar(`/documentos/${d.id}/download`, d.nome_original)}><Download size={17}/></button></td></tr>)}</tbody></table></div>}
    {dados && <Paginacao pagina={dados.documentos.pagina} paginas={dados.documentos.paginas} mudar={setPagina}/>}
    {novaPasta && <ModalNovaPasta superior={pastaId} fechar={() => setNovaPasta(false)} concluir={() => { setNovaPasta(false); atualizar(); }}/>}
    {upload && pastaId && <ModalUpload pastaId={pastaId} fechar={() => setUpload(false)} concluir={(id) => { setUpload(false); avisar('Documento enviado com sucesso.'); atualizar(); if (id) navegar(`/documentos/${id}`); }}/>} 
  </>;
}

function ModalNovaPasta({ superior, fechar, concluir }: { superior: string | null; fechar: () => void; concluir: () => void }) {
  const avisar = useAviso(); const [nome, setNome] = useState(''); const [descricao, setDescricao] = useState(''); const [classificacao, setClassificacao] = useState('interno'); const [salvando, setSalvando] = useState(false);
  async function salvar(e: React.FormEvent) { e.preventDefault(); setSalvando(true); try { await api.post('/pastas', { nome, descricao: descricao || null, pasta_superior_id: superior, classificacao, cor: '#2563eb', icone: 'folder' }); avisar('Pasta criada com sucesso.'); concluir(); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha ao criar pasta.', 'erro'); } finally { setSalvando(false); } }
  return <Modal titulo="Nova pasta" fechar={fechar} rodape={<><button className="botao" onClick={fechar}>Cancelar</button><button className="botao principal" form="form-pasta" disabled={salvando || !nome.trim()}>Criar pasta</button></>}><form id="form-pasta" onSubmit={salvar}><div className="campo"><label>Nome <span className="obrigatorio">*</span></label><input autoFocus value={nome} onChange={(e) => setNome(e.target.value)} required maxLength={255}/></div><div className="campo"><label>Descrição</label><textarea value={descricao} onChange={(e) => setDescricao(e.target.value)}/></div><div className="campo"><label>Classificação</label><select value={classificacao} onChange={(e) => setClassificacao(e.target.value)}><option value="publico">Público</option><option value="interno">Interno</option><option value="restrito">Restrito</option><option value="confidencial">Confidencial</option><option value="sigiloso">Sigiloso</option></select></div></form></Modal>;
}

function ModalUpload({ pastaId, fechar, concluir }: { pastaId: string; fechar: () => void; concluir: (id?: string) => void }) {
  const avisar = useAviso(); const input = useRef<HTMLInputElement>(null); const [arquivo, setArquivo] = useState<File>(); const [nome, setNome] = useState(''); const [descricao, setDescricao] = useState(''); const [classificacao, setClassificacao] = useState('interno'); const [etiquetas, setEtiquetas] = useState(''); const [progresso, setProgresso] = useState(0); const [enviando, setEnviando] = useState(false);
  async function enviar(e: React.FormEvent) { e.preventDefault(); if (!arquivo) return; setEnviando(true); const form = new FormData(); form.append('pasta_id', pastaId); form.append('arquivo', arquivo); form.append('metadados', JSON.stringify({ nome_exibicao: nome || arquivo.name, descricao: descricao || null, classificacao, etiquetas: etiquetas.split(',').map((v) => v.trim()).filter(Boolean) }));
    try { let resultado = await enviarArquivo('/documentos/upload', form, setProgresso).promessa; if (resultado.duplicado) { if (!window.confirm(`${resultado.duplicado.mensagem}\nDeseja manter uma nova cópia?`)) { setEnviando(false); return; } form.append('acao_duplicidade', 'novo_documento'); resultado = await enviarArquivo('/documentos/upload', form, setProgresso).promessa; } concluir(resultado.documento?.id); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha no envio.', 'erro'); setEnviando(false); } }
  return <Modal titulo="Enviar documento" fechar={fechar} largo rodape={<><button className="botao" onClick={fechar}>Cancelar</button><button className="botao principal" form="form-upload" disabled={!arquivo || enviando}><Upload size={17}/>{enviando ? `Enviando ${progresso}%` : 'Enviar documento'}</button></>}><form id="form-upload" onSubmit={enviar}><div className="area-solta" onClick={() => input.current?.click()}><FilePlus2 size={38}/><strong>{arquivo ? arquivo.name : 'Selecione um arquivo'}</strong><span>{arquivo ? formatarBytes(arquivo.size) : 'Clique aqui para procurar no computador'}</span><input ref={input} hidden type="file" onChange={(e) => { const f = e.target.files?.[0]; setArquivo(f); if (f) setNome(f.name); }}/></div>{enviando && <div className="progresso margem-topo"><div className="barra" style={{ width: `${progresso}%` }}/></div>}<div className="linha-campos margem-topo"><div className="campo"><label>Nome de exibição</label><input value={nome} onChange={(e) => setNome(e.target.value)}/></div><div className="campo"><label>Classificação</label><select value={classificacao} onChange={(e) => setClassificacao(e.target.value)}><option value="publico">Público</option><option value="interno">Interno</option><option value="restrito">Restrito</option><option value="confidencial">Confidencial</option><option value="sigiloso">Sigiloso</option></select></div></div><div className="campo"><label>Descrição</label><textarea value={descricao} onChange={(e) => setDescricao(e.target.value)}/></div><div className="campo"><label>Etiquetas</label><input value={etiquetas} onChange={(e) => setEtiquetas(e.target.value)} placeholder="Ex.: contrato, 2026, licitação"/><div className="ajuda">Separe as etiquetas por vírgulas.</div></div></form></Modal>;
}

