import { ArrowLeft, Download, Eye, FileCheck2, FileText, Heart, History, Lock, Pencil, ShieldCheck, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api, baixar, carregarPrevia, ErroApi } from '../api/cliente';
import { Carregando, Chip, ErroEstado, Modal } from '../componentes/Comuns';
import { useAviso } from '../contexto/AvisoContexto';
import type { Documento } from '../types';
import { formatarBytes, formatarData, rotulo } from '../utils';

export function DocumentoDetalhe() {
  const { id = '' } = useParams(); const navegar = useNavigate(); const avisar = useAviso(); const [doc, setDoc] = useState<Documento>(); const [erro, setErro] = useState(''); const [aba, setAba] = useState('detalhes'); const [previa, setPrevia] = useState<{ url: string; tipo: string }>(); const [editando, setEditando] = useState(false); const [chave, setChave] = useState(0);
  useEffect(() => { api.get<Documento>(`/documentos/${id}`).then(setDoc).catch((e) => setErro(e instanceof ErroApi ? e.message : 'Falha ao abrir documento.')); return () => { if (previa) URL.revokeObjectURL(previa.url); }; }, [id, chave]);
  async function visualizar() { try { const p = await carregarPrevia(id); setPrevia(p); setAba('visualizar'); } catch (e) { avisar(e instanceof Error ? e.message : 'Prévia indisponível.', 'erro'); } }
  async function acao(caminho: string, texto: string, metodo: 'post' | 'del' = 'post') { try { await api[metodo](caminho); avisar(texto); setChave((v) => v + 1); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha na operação.', 'erro'); } }
  async function excluir() { if (!confirm('Enviar este documento para a lixeira?')) return; try { await api.del(`/documentos/${id}`, { motivo: 'Excluído pela interface web' }); avisar('Documento enviado para a lixeira.'); navegar('/documentos'); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha ao excluir.', 'erro'); } }
  if (!doc && !erro) return <Carregando texto="Abrindo documento…"/>; if (erro || !doc) return <ErroEstado mensagem={erro || 'Documento não encontrado.'}/>;
  return <><Link className="voltar" to={`/arquivos?pasta=${doc.pasta_id}`}><ArrowLeft size={17}/> Voltar à pasta</Link><div className="cabecalho-pagina documento-cabecalho"><div className="titulo-documento"><FileText size={36}/><div><h1>{doc.nome_exibicao}</h1><p className="subtitulo">{doc.codigo} · {doc.nome_original} · versão {doc.versao_atual}</p></div></div><div className="barra-acoes"><button className="botao" onClick={() => acao(`/documentos/${id}/favorito`, doc.favorito ? 'Removido dos favoritos.' : 'Adicionado aos favoritos.')}><Heart size={17} fill={doc.favorito ? 'currentColor' : 'none'}/> {doc.favorito ? 'Favorito' : 'Favoritar'}</button><button className="botao" onClick={visualizar}><Eye size={17}/> Visualizar</button><button className="botao principal" onClick={() => baixar(`/documentos/${id}/download`, doc.nome_original)}><Download size={17}/> Baixar</button></div></div>
  <div className="abas"><button className={`aba ${aba === 'detalhes' ? 'ativa' : ''}`} onClick={() => setAba('detalhes')}>Detalhes</button><button className={`aba ${aba === 'visualizar' ? 'ativa' : ''}`} onClick={visualizar}>Visualização</button><button className={`aba ${aba === 'historico' ? 'ativa' : ''}`} onClick={() => setAba('historico')}>Histórico</button></div>
  {aba === 'detalhes' && <div className="grade detalhe-documento"><section className="cartao"><div className="entre"><div className="cartao-titulo"><FileCheck2 size={19}/> Informações do documento</div>{doc.permissoes.includes('edit_metadata') && <button className="botao pequeno" onClick={() => setEditando(true)}><Pencil size={15}/> Editar</button>}</div><div className="definicoes"><div><div className="rotulo">Classificação</div><div className="valor"><Chip>{rotulo(doc.classificacao)}</Chip></div></div><div><div className="rotulo">Situação</div><div className="valor"><Chip>{rotulo(doc.situacao)}</Chip></div></div><div><div className="rotulo">Pasta</div><div className="valor"><Link to={`/arquivos?pasta=${doc.pasta_id}`}>{doc.pasta_nome || 'Abrir pasta'}</Link></div></div><div><div className="rotulo">Responsável</div><div className="valor">{doc.responsavel_nome || 'Não informado'}</div></div><div><div className="rotulo">Categoria</div><div className="valor">{doc.categoria_nome || 'Sem categoria'}</div></div><div><div className="rotulo">Data do documento</div><div className="valor">{formatarData(doc.data_documento)}</div></div><div><div className="rotulo">Validade</div><div className="valor">{formatarData(doc.data_validade)}</div></div><div><div className="rotulo">Processo</div><div className="valor">{doc.numero_processo || '—'}</div></div><div><div className="rotulo">Autor</div><div className="valor">{doc.autor || '—'}</div></div><div><div className="rotulo">Criado em</div><div className="valor">{formatarData(doc.criado_em, true)}</div></div></div>{doc.descricao && <div className="bloco-descricao"><strong>Descrição</strong><p>{doc.descricao}</p></div>}{doc.etiquetas.length > 0 && <div className="barra-acoes">{doc.etiquetas.map((t) => <Chip cor="azul" key={t}>{t}</Chip>)}</div>}</section>
  <aside className="pilha"><section className="cartao"><div className="cartao-titulo"><ShieldCheck size={19}/> Arquivo e integridade</div><div className="definicoes uma-coluna"><div><div className="rotulo">Tamanho</div><div className="valor">{formatarBytes(doc.tamanho_bytes)}</div></div><div><div className="rotulo">Formato</div><div className="valor">{doc.mime || doc.extensao}</div></div><div><div className="rotulo">SHA-256</div><div className="valor mono quebra">{doc.sha256 || 'Processando…'}</div></div><div><div className="rotulo">Indexação</div><div className="valor">{rotulo(doc.situacao_indexacao)}</div></div></div>{doc.bloqueio_legal && <div className="aviso atencao margem-topo"><Lock size={18}/> Sob bloqueio legal</div>}</section><section className="cartao"><div className="cartao-titulo">Estatísticas</div><div className="mini-indicadores vertical"><span><Eye size={17}/><strong>{doc.total_visualizacoes}</strong> visualizações</span><span><Download size={17}/><strong>{doc.total_downloads}</strong> downloads</span><span><History size={17}/><strong>{doc.versao_atual}</strong> versões</span></div></section>{doc.permissoes.includes('delete') && <button className="botao perigo" onClick={excluir}><Trash2 size={17}/> Enviar para a lixeira</button>}</aside></div>}
  {aba === 'visualizar' && <section className="cartao">{!previa ? <Carregando texto="Preparando visualização…"/> : previa.tipo.startsWith('image/') ? <div className="visualizador"><img src={previa.url} alt={doc.nome_exibicao}/></div> : previa.tipo === 'application/pdf' ? <iframe className="quadro-previa" src={previa.url} title={`Visualização de ${doc.nome_exibicao}`}/> : <div className="aviso info">Este formato não possui visualização integrada. Use o botão Baixar.</div>}</section>}
  {aba === 'historico' && <Historico id={id}/>} {editando && <EditarDocumento doc={doc} fechar={() => setEditando(false)} concluir={() => { setEditando(false); setChave((v) => v + 1); }}/>}</>;
}

function Historico({ id }: { id: string }) { const [itens, setItens] = useState<any[]>(); useEffect(() => { api.get<any>(`/documentos/${id}/historico`).then((r) => setItens(Array.isArray(r) ? r : r.itens || [])).catch(() => setItens([])); }, [id]); if (!itens) return <Carregando/>; return <section className="cartao"><div className="linha-tempo">{itens.map((i, n) => <div key={i.id || n}><span className="ponto ok"/><p><strong>{rotulo(i.acao || i.tipo)}</strong><small>{i.usuario_nome || i.usuario || 'Sistema'} · {formatarData(i.criado_em || i.quando, true)}</small></p></div>)}</div>{!itens.length && <p className="texto-secundario">Nenhum evento adicional registrado.</p>}</section>; }

function EditarDocumento({ doc, fechar, concluir }: { doc: Documento; fechar: () => void; concluir: () => void }) { const avisar = useAviso(); const [nome, setNome] = useState(doc.nome_exibicao); const [descricao, setDescricao] = useState(doc.descricao || ''); const [classificacao, setClassificacao] = useState(doc.classificacao); const [situacao, setSituacao] = useState(doc.situacao); const [salvando, setSalvando] = useState(false); async function salvar(e: React.FormEvent) { e.preventDefault(); setSalvando(true); try { await api.put(`/documentos/${doc.id}`, { nome_exibicao: nome, descricao, classificacao, situacao, versao_controle: doc.versao_controle }); avisar('Documento atualizado.'); concluir(); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha ao atualizar.', 'erro'); } finally { setSalvando(false); } } return <Modal titulo="Editar informações" fechar={fechar} rodape={<><button className="botao" onClick={fechar}>Cancelar</button><button className="botao principal" form="editar-doc" disabled={salvando}>Salvar alterações</button></>}><form id="editar-doc" onSubmit={salvar}><div className="campo"><label>Nome</label><input value={nome} onChange={(e) => setNome(e.target.value)} required/></div><div className="campo"><label>Descrição</label><textarea value={descricao} onChange={(e) => setDescricao(e.target.value)}/></div><div className="linha-campos"><div className="campo"><label>Classificação</label><select value={classificacao} onChange={(e) => setClassificacao(e.target.value)}>{['publico','interno','restrito','confidencial','sigiloso'].map((v) => <option key={v} value={v}>{rotulo(v)}</option>)}</select></div><div className="campo"><label>Situação</label><select value={situacao} onChange={(e) => setSituacao(e.target.value)}>{['rascunho','aguardando_revisao','em_revisao','aguardando_aprovacao','aprovado','rejeitado','arquivado','cancelado'].map((v) => <option key={v} value={v}>{rotulo(v)}</option>)}</select></div></div></form></Modal>; }
