import { Download, FileSearch, FileText, Filter, Heart, Search, SlidersHorizontal } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { api, baixar, ErroApi } from '../api/cliente';
import { Carregando, Chip, ErroEstado, Paginacao, Vazio } from '../componentes/Comuns';
import { useAviso } from '../contexto/AvisoContexto';
import type { Categoria, Documento, Pagina, Secretaria } from '../types';
import { formatarBytes, formatarData, parametros, rotulo } from '../utils';

export function Documentos({ modo }: { modo?: 'recentes' | 'favoritos' }) {
  const [url, setUrl] = useSearchParams(); const avisar = useAviso();
  const [dados, setDados] = useState<Pagina<Documento>>(); const [categorias, setCategorias] = useState<Categoria[]>([]); const [secretarias, setSecretarias] = useState<Secretaria[]>([]);
  const [carregando, setCarregando] = useState(true); const [erro, setErro] = useState(''); const [filtros, setFiltros] = useState(false); const [chave, setChave] = useState(0);
  const pagina = Number(url.get('pagina') || 1); const termo = url.get('termo') || '';
  useEffect(() => { Promise.all([api.get<Categoria[]>('/categorias'), api.get<Secretaria[]>('/secretarias')]).then(([c, s]) => { setCategorias(c); setSecretarias(s); }).catch(() => undefined); }, []);
  useEffect(() => {
    setCarregando(true); setErro(''); const q: Record<string, unknown> = Object.fromEntries(url.entries()); q.por_pagina = 25; if (modo === 'recentes') q.recentes = true; if (modo === 'favoritos') q.favoritos = true;
    api.get<Pagina<Documento>>(`/documentos${parametros(q)}`).then(setDados).catch((e) => setErro(e instanceof ErroApi ? e.message : 'Falha ao consultar documentos.')).finally(() => setCarregando(false));
  }, [url, modo, chave]);
  function alterar(chave: string, valor: string) { const nova = new URLSearchParams(url); if (valor) nova.set(chave, valor); else nova.delete(chave); nova.delete('pagina'); setUrl(nova); }
  async function favorito(doc: Documento) { try { await api.post(`/documentos/${doc.id}/favorito`); avisar(doc.favorito ? 'Removido dos favoritos.' : 'Adicionado aos favoritos.'); setChave((v) => v + 1); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha na ação.', 'erro'); } }
  const titulo = modo === 'recentes' ? 'Documentos recentes' : modo === 'favoritos' ? 'Favoritos' : 'Todos os documentos';
  return <>
    <div className="cabecalho-pagina"><div><h1>{titulo}</h1><p className="subtitulo">Localize documentos por metadados, conteúdo e classificação.</p></div><button className="botao" onClick={() => setFiltros(!filtros)}><SlidersHorizontal size={17}/> Filtros {Array.from(url.keys()).filter((k) => !['termo', 'pagina'].includes(k)).length > 0 && <span className="contador-filtro">{Array.from(url.keys()).filter((k) => !['termo', 'pagina'].includes(k)).length}</span>}</button></div>
    <div className="cartao barra-pesquisa"><Search size={20}/><input type="search" value={termo} onChange={(e) => alterar('termo', e.target.value)} placeholder="Busque por nome, código, processo, protocolo ou texto do documento…"/></div>
    {filtros && <div className="cartao painel-filtros"><div className="linha-campos"><div className="campo"><label>Secretaria</label><select value={url.get('secretaria_id') || ''} onChange={(e) => alterar('secretaria_id', e.target.value)}><option value="">Todas</option>{secretarias.map((s) => <option value={s.id} key={s.id}>{s.nome}</option>)}</select></div><div className="campo"><label>Categoria</label><select value={url.get('categoria_id') || ''} onChange={(e) => alterar('categoria_id', e.target.value)}><option value="">Todas</option>{categorias.map((c) => <option value={c.id} key={c.id}>{c.nome}</option>)}</select></div><div className="campo"><label>Classificação</label><select value={url.get('classificacao') || ''} onChange={(e) => alterar('classificacao', e.target.value)}><option value="">Todas</option><option value="publico">Público</option><option value="interno">Interno</option><option value="restrito">Restrito</option><option value="confidencial">Confidencial</option><option value="sigiloso">Sigiloso</option></select></div><div className="campo"><label>Ano de referência</label><input type="number" min="1900" max="2200" value={url.get('ano') || ''} onChange={(e) => alterar('ano', e.target.value)}/></div></div><button className="botao pequeno" onClick={() => setUrl(termo ? { termo } : {})}>Limpar filtros</button></div>}
    {carregando ? <Carregando texto="Consultando o acervo…"/> : erro ? <ErroEstado mensagem={erro} tentar={() => setChave((v) => v + 1)}/> : !dados?.itens.length ? <Vazio titulo="Nenhum documento encontrado" texto="Revise os filtros ou use um termo de busca mais amplo."/> : <><div className="entre resumo-lista"><span><strong>{dados.total.toLocaleString('pt-BR')}</strong> documento(s) encontrado(s)</span><select value={url.get('ordenar') || 'alteracao'} onChange={(e) => alterar('ordenar', e.target.value)} aria-label="Ordenar"><option value="alteracao">Mais recentes</option><option value="nome">Nome</option><option value="tamanho">Tamanho</option><option value="criacao">Data de criação</option></select></div><div className="tabela-rolagem"><table className="tabela"><thead><tr><th>Documento</th><th>Local</th><th>Classificação</th><th>Situação</th><th>Atualizado</th><th className="numerico">Tamanho</th><th><span className="somente-leitores">Ações</span></th></tr></thead><tbody>{dados.itens.map((doc) => <tr key={doc.id}><td><div className="celula-principal"><FileText size={22}/><div><Link className="nome" to={`/documentos/${doc.id}`}>{doc.nome_exibicao}</Link><div className="celula-secundaria">{doc.codigo} · {doc.extensao?.toUpperCase()} · v{doc.versao_atual}</div></div></div></td><td><Link to={`/arquivos?pasta=${doc.pasta_id}`}>{doc.pasta_nome || 'Abrir pasta'}</Link><div className="celula-secundaria">{doc.secretaria_nome}</div></td><td><Chip cor={doc.classificacao === 'publico' ? 'verde' : doc.classificacao === 'interno' ? 'azul' : doc.classificacao === 'sigiloso' ? 'vermelho' : 'amarelo'}>{rotulo(doc.classificacao)}</Chip></td><td><Chip>{rotulo(doc.situacao)}</Chip></td><td>{formatarData(doc.atualizado_em)}</td><td className="numerico">{formatarBytes(doc.tamanho_bytes)}</td><td><div className="acoes-linha"><button className="botao sutil icone" title="Favoritar" onClick={() => favorito(doc)}><Heart size={17} fill={doc.favorito ? 'currentColor' : 'none'}/></button><button className="botao sutil icone" title="Baixar" onClick={() => baixar(`/documentos/${doc.id}/download`, doc.nome_original)}><Download size={17}/></button></div></td></tr>)}</tbody></table></div><Paginacao pagina={dados.pagina} paginas={dados.paginas} mudar={(p) => alterar('pagina', String(p))}/></>}
  </>;
}

