import { ArchiveRestore, CheckCircle2, DatabaseBackup, Download, ExternalLink, FileWarning, Link2, Play, RefreshCw, Search, ShieldCheck, Trash2, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, baixar, ErroApi } from '../api/cliente';
import { Carregando, Chip, ErroEstado, Vazio } from '../componentes/Comuns';
import { useAviso } from '../contexto/AvisoContexto';
import type { Pagina, Secretaria, Setor, Usuario } from '../types';
import { formatarBytes, formatarData, rotulo } from '../utils';

export function Compartilhados() {
  const [aba, setAba] = useState('comigo'); const [itens, setItens] = useState<any[]>(); const [links, setLinks] = useState<Pagina<any>>(); const [erro, setErro] = useState('');
  useEffect(() => { setItens(undefined); setLinks(undefined); const pedido = aba === 'links' ? api.get<Pagina<any>>('/links-externos') : api.get<any[]>(`/compartilhamentos/${aba === 'comigo' ? 'comigo' : 'por-mim'}`); pedido.then((r: any) => aba === 'links' ? setLinks(r) : setItens(r)).catch((e) => setErro(e.message)); }, [aba]);
  const lista = aba === 'links' ? links?.itens : itens;
  return <><div className="cabecalho-pagina"><div><h1>Compartilhamentos</h1><p className="subtitulo">Acompanhe conteúdos recebidos, enviados e links externos.</p></div></div><div className="abas"><button className={`aba ${aba === 'comigo' ? 'ativa' : ''}`} onClick={() => setAba('comigo')}>Comigo</button><button className={`aba ${aba === 'por-mim' ? 'ativa' : ''}`} onClick={() => setAba('por-mim')}>Por mim</button><button className={`aba ${aba === 'links' ? 'ativa' : ''}`} onClick={() => setAba('links')}>Links externos</button></div>{erro ? <ErroEstado mensagem={erro}/> : !lista ? <Carregando/> : !lista.length ? <Vazio titulo="Nenhum compartilhamento" texto="Os itens compartilhados aparecerão aqui."/> : <div className="tabela-rolagem"><table className="tabela"><thead><tr><th>Recurso</th><th>{aba === 'comigo' ? 'Compartilhado por' : aba === 'links' ? 'Criado por' : 'Destino'}</th><th>Permissões / acesso</th><th>Situação</th><th>Data</th></tr></thead><tbody>{lista.map((i: any) => <tr key={i.id}><td><div className="celula-principal"><Link2 size={20}/><div>{i.recurso_id ? <Link className="nome" to={i.recurso_tipo === 'folder' ? `/arquivos?pasta=${i.recurso_id}` : `/documentos/${i.recurso_id}`}>{i.recurso_nome || 'Recurso'}</Link> : <span className="nome">{i.nome}</span>}<div className="celula-secundaria">{i.local_original || i.itens?.map((x: any) => x.nome).join(', ')}</div></div></div></td><td>{i.compartilhado_por_nome || i.destino_nome || i.criado_por_nome || '—'}</td><td>{i.permissoes?.map((p: string) => <Chip key={p}>{rotulo(p)}</Chip>) || `${i.total_acessos || 0} acesso(s)`}</td><td><Chip cor={(i.ativo ?? !i.revogado_em) ? 'verde' : 'cinza'}>{(i.ativo ?? !i.revogado_em) ? 'Ativo' : 'Encerrado'}</Chip></td><td>{formatarData(i.criado_em, true)}</td></tr>)}</tbody></table></div>}</>;
}

export function Lixeira() {
  const avisar = useAviso(); const [dados, setDados] = useState<any>(); const [chave, setChave] = useState(0); const [termo, setTermo] = useState('');
  useEffect(() => { api.get(`/lixeira?termo=${encodeURIComponent(termo)}`).then(setDados).catch((e) => avisar(e.message, 'erro')); }, [chave, termo]);
  async function restaurar(i: any) { try { await api.post(`/lixeira/${i.tipo === 'pasta' ? 'pastas' : 'documentos'}/${i.id}/restaurar`, { pasta_destino_id: null }); avisar('Item restaurado.'); setChave((v) => v + 1); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha ao restaurar.', 'erro'); } }
  return <><div className="cabecalho-pagina"><div><h1>Lixeira</h1><p className="subtitulo">Itens excluídos permanecem por {dados?.prazo_retencao_dias || '—'} dias antes da remoção definitiva.</p></div></div><div className="cartao barra-pesquisa"><Search size={19}/><input value={termo} onChange={(e) => setTermo(e.target.value)} placeholder="Filtrar itens excluídos…"/></div>{!dados ? <Carregando/> : !dados.itens.length ? <Vazio titulo="A lixeira está vazia"/> : <div className="tabela-rolagem"><table className="tabela"><thead><tr><th>Item</th><th>Excluído por</th><th>Data</th><th>Motivo</th><th>Tamanho</th><th>Ações</th></tr></thead><tbody>{dados.itens.map((i: any) => <tr key={i.id}><td><div className="celula-principal"><Trash2 size={20}/><div><span className="nome">{i.nome}</span><div className="celula-secundaria">{rotulo(i.tipo)} {i.codigo && `· ${i.codigo}`}</div></div></div></td><td>{i.excluido_por || '—'}</td><td>{formatarData(i.excluido_em, true)}</td><td>{i.motivo || '—'}</td><td>{formatarBytes(i.tamanho_bytes)}</td><td><button className="botao pequeno" onClick={() => restaurar(i)}><ArchiveRestore size={16}/> Restaurar</button></td></tr>)}</tbody></table></div>}</>;
}

export function Recebimentos() {
  const avisar = useAviso(); const [aba, setAba] = useState('recebimentos'); const [itens, setItens] = useState<any[]>(); const [chave, setChave] = useState(0);
  useEffect(() => { setItens(undefined); api.get<any[]>(aba === 'recebimentos' ? '/recebimentos' : '/solicitacoes-externas').then(setItens).catch((e) => avisar(e.message, 'erro')); }, [aba, chave]);
  async function analisar(id: string, acao: string) { const observacao = acao === 'aprovar' ? undefined : prompt('Informe uma observação:') || undefined; try { await api.post(`/recebimentos/${id}/analisar`, { acao, observacao }); avisar('Análise registrada.'); setChave((v) => v + 1); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha na análise.', 'erro'); } }
  return <><div className="cabecalho-pagina"><div><h1>Recebimentos externos</h1><p className="subtitulo">Analise arquivos enviados por cidadãos, fornecedores e parceiros.</p></div></div><div className="abas"><button className={`aba ${aba === 'recebimentos' ? 'ativa' : ''}`} onClick={() => setAba('recebimentos')}>Arquivos recebidos</button><button className={`aba ${aba === 'solicitacoes' ? 'ativa' : ''}`} onClick={() => setAba('solicitacoes')}>Solicitações</button></div>{!itens ? <Carregando/> : !itens.length ? <Vazio titulo="Nenhum recebimento"/> : <div className="tabela-rolagem"><table className="tabela"><thead><tr><th>{aba === 'recebimentos' ? 'Arquivo' : 'Solicitação'}</th><th>Remetente / responsável</th><th>Destino</th><th>Situação</th><th>Recebido / criado</th><th>Ações</th></tr></thead><tbody>{itens.map((i: any) => <tr key={i.id}><td><strong>{i.nome_original || i.titulo}</strong><div className="celula-secundaria">{i.solicitacao_titulo || `${i.total_recebidos} recebido(s)`}</div></td><td>{i.remetente_nome || i.responsavel_nome || '—'}<div className="celula-secundaria">{i.remetente_email}</div></td><td>{i.pasta_destino_nome || '—'}</td><td><Chip cor={['aprovado','incorporado'].includes(i.situacao) || i.ativo ? 'verde' : i.situacao === 'rejeitado' ? 'vermelho' : 'amarelo'}>{rotulo(i.situacao || (i.ativo ? 'ativo' : 'encerrado'))}</Chip></td><td>{formatarData(i.recebido_em || i.criado_em, true)}</td><td>{aba === 'recebimentos' && ['recebido','em_analise'].includes(i.situacao) && <div className="barra-acoes"><button className="botao pequeno principal" onClick={() => analisar(i.id, 'aprovar')}>Aprovar</button><button className="botao pequeno" onClick={() => analisar(i.id, 'rejeitar')}>Rejeitar</button></div>}</td></tr>)}</tbody></table></div>}</>;
}

export function Auditoria() {
  const [dados, setDados] = useState<Pagina<any>>(); const [erro, setErro] = useState(''); const [resultado, setResultado] = useState('');
  useEffect(() => { api.get<Pagina<any>>(`/auditoria?por_pagina=50${resultado ? `&resultado=${resultado}` : ''}`).then(setDados).catch((e) => setErro(e.message)); }, [resultado]);
  return <><div className="cabecalho-pagina"><div><h1>Auditoria</h1><p className="subtitulo">Trilha imutável das ações realizadas no GovDoc.</p></div><button className="botao" onClick={() => baixar('/auditoria/exportar', 'auditoria-govdoc.csv')}><Download size={17}/> Exportar CSV</button></div><div className="cartao filtros-compactos"><label>Resultado <select value={resultado} onChange={(e) => setResultado(e.target.value)}><option value="">Todos</option><option value="sucesso">Sucesso</option><option value="negado">Negado</option><option value="falha">Falha</option></select></label></div>{erro ? <ErroEstado mensagem={erro}/> : !dados ? <Carregando/> : <div className="tabela-rolagem"><table className="tabela"><thead><tr><th>Data e hora</th><th>Usuário</th><th>Ação</th><th>Recurso</th><th>Resultado</th><th>IP</th></tr></thead><tbody>{dados.itens.map((i) => <tr key={i.id}><td>{formatarData(i.data_hora, true)}</td><td>{i.usuario_nome || 'Sistema'}</td><td>{rotulo(i.acao)}</td><td>{i.recurso_nome || rotulo(i.recurso_tipo)}</td><td><Chip cor={i.resultado === 'sucesso' ? 'verde' : 'vermelho'}>{rotulo(i.resultado)}</Chip></td><td className="mono">{i.ip || '—'}</td></tr>)}</tbody></table></div>}</>;
}

export function Backups() {
  const avisar = useAviso(); const [dados, setDados] = useState<any>(); const [chave, setChave] = useState(0);
  useEffect(() => { api.get('/backups/painel').then(setDados).catch((e) => avisar(e.message, 'erro')); }, [chave]);
  async function executar(id: string) { try { avisar('Backup iniciado.', 'info'); await api.post(`/backups/agendamentos/${id}/executar`, {}); avisar('Backup concluído.'); setChave((v) => v + 1); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha no backup.', 'erro'); } }
  async function verificar(id: string) { try { await api.post(`/backups/execucoes/${id}/verificar`); avisar('Integridade verificada.'); setChave((v) => v + 1); } catch (e) { avisar(e instanceof Error ? e.message : 'Falha na verificação.', 'erro'); } }
  return <><div className="cabecalho-pagina"><div><h1>Backups</h1><p className="subtitulo">Proteção, integridade e histórico de recuperação do acervo.</p></div></div>{!dados ? <Carregando/> : <><div className={`aviso ${dados.backup_habilitado ? 'sucesso' : 'atencao'}`}><DatabaseBackup size={21}/><div className="texto"><div className="titulo">{dados.backup_habilitado ? 'Rotina de backup habilitada' : 'Backup desabilitado'}</div>{dados.aviso_destino}</div></div><div className="grade col-3 margem-topo">{dados.agendamentos.map((j: any) => <div className="cartao" key={j.id}><div className="entre"><strong>{j.nome}</strong><Chip cor={j.ativo ? 'verde' : 'cinza'}>{j.ativo ? 'Ativo' : 'Inativo'}</Chip></div><p className="texto-secundario">{rotulo(j.tipo)} · agenda <span className="mono">{j.agendamento_cron}</span></p><button className="botao pequeno principal" onClick={() => executar(j.id)}><Play size={15}/> Executar agora</button></div>)}</div><h2 className="margem-topo">Histórico recente</h2><div className="tabela-rolagem"><table className="tabela"><thead><tr><th>Início</th><th>Tipo</th><th>Situação</th><th>Arquivos</th><th>Tamanho</th><th>Integridade</th><th>Ação</th></tr></thead><tbody>{dados.historico.map((i: any) => <tr key={i.id}><td>{formatarData(i.iniciado_em, true)}</td><td>{rotulo(i.tipo)}</td><td><Chip cor={i.situacao === 'concluido' ? 'verde' : i.situacao === 'falhou' ? 'vermelho' : 'amarelo'}>{rotulo(i.situacao)}</Chip></td><td>{i.total_arquivos}</td><td>{formatarBytes(i.tamanho_bytes)}</td><td>{i.verificado_em ? <Chip cor="verde"><ShieldCheck size={13}/> Verificado</Chip> : 'Pendente'}</td><td><button className="botao pequeno" onClick={() => verificar(i.id)}><RefreshCw size={14}/> Verificar</button></td></tr>)}</tbody></table></div></>}</>;
}

