import { Download, FileText, LockKeyhole, Send, ShieldCheck, Upload } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { ErroApi, requisitar, urlPublica } from '../api/cliente';
import { Carregando, Chip, ErroEstado, Vazio } from '../componentes/Comuns';
import { formatarBytes, formatarData } from '../utils';

export function AcessoPublico() {
  const { token = '' } = useParams(); const [info, setInfo] = useState<any>(); const [aberto, setAberto] = useState<any>(); const [form, setForm] = useState({ senha: '', nome: '', email: '', telefone: '' }); const [erro, setErro] = useState(''); const [abrindo, setAbrindo] = useState(false);
  useEffect(() => { requisitar(`/publico/acesso/${token}`, { publico: true }).then(setInfo).catch((e) => setErro(e.message)); }, [token]);
  async function abrir(e: React.FormEvent) { e.preventDefault(); setAbrindo(true); setErro(''); try { setAberto(await requisitar(`/publico/acesso/${token}`, { metodo: 'POST', corpo: form, publico: true })); } catch (e) { setErro(e instanceof Error ? e.message : 'Não foi possível abrir o compartilhamento.'); } finally { setAbrindo(false); } }
  if (!info && !erro) return <div className="pagina-publica"><Carregando/></div>; if (!info) return <div className="pagina-publica"><ErroEstado mensagem={erro}/></div>;
  return <main className="pagina-publica"><section className="publico-caixa"><header className="publico-cabecalho" style={{ background: info.cor_primaria }}><h1>{info.nome}</h1><p>{info.instituicao}</p></header><div className="publico-corpo">{!aberto ? <><p>{info.descricao}</p>{erro && <div className="aviso erro">{erro}</div>}<form onSubmit={abrir}>{info.exige_senha && <div className="campo"><label>Senha de acesso</label><input type="password" required value={form.senha} onChange={(e) => setForm({...form, senha: e.target.value})}/></div>}{info.exigir_nome && <div className="campo"><label>Seu nome</label><input required value={form.nome} onChange={(e) => setForm({...form, nome: e.target.value})}/></div>}{info.exigir_email && <div className="campo"><label>Seu e-mail</label><input type="email" required value={form.email} onChange={(e) => setForm({...form, email: e.target.value})}/></div>}{info.exigir_telefone && <div className="campo"><label>Telefone</label><input required value={form.telefone} onChange={(e) => setForm({...form, telefone: e.target.value})}/></div>}{info.termo_responsabilidade && <label className="caixa-marcacao"><input type="checkbox" required/> <span>Li e aceito: {info.termo_responsabilidade}</span></label>}<button className="botao principal" disabled={abrindo}><LockKeyhole size={17}/> Acessar documentos</button></form></> : <><div className="aviso sucesso"><ShieldCheck size={20}/><div className="texto"><div className="titulo">Acesso autorizado</div>Esta sessão é temporária e restrita a estes documentos.</div></div><h2 className="margem-topo">Documentos compartilhados</h2>{!aberto.documentos.length ? <Vazio titulo="Nenhum documento disponível"/> : <div className="pilha">{aberto.documentos.map((d: any) => <div className="item-publico" key={d.id}><FileText size={25}/><span><strong>{d.nome}</strong><small>{d.codigo} · {formatarBytes(d.tamanho_bytes)} · {formatarData(d.atualizado_em)}</small></span>{aberto.permitir_download && <a className="botao pequeno" href={`${urlPublica(`/publico/acesso/documentos/${d.id}/download`)}?sessao=${encodeURIComponent(aberto.sessao)}`}><Download size={16}/> Baixar</a>}</div>)}</div>}</>}</div></section></main>;
}

export function EnvioPublico() {
  const { token = '' } = useParams(); const [info, setInfo] = useState<any>(); const [arquivo, setArquivo] = useState<File>(); const [form, setForm] = useState({ nome: '', email: '', telefone: '', senha: '', observacao: '' }); const [erro, setErro] = useState(''); const [sucesso, setSucesso] = useState(''); const [enviando, setEnviando] = useState(false);
  useEffect(() => { requisitar(`/publico/envio/${token}`, { publico: true }).then(setInfo).catch((e) => setErro(e.message)); }, [token]);
  async function enviar(e: React.FormEvent) { e.preventDefault(); if (!arquivo) return; setEnviando(true); setErro(''); const dados = new FormData(); dados.append('arquivo', arquivo); Object.entries(form).forEach(([k,v]) => { if (v) dados.append(k,v); }); try { const r = await requisitar<any>(`/publico/envio/${token}`, { metodo: 'POST', formulario: dados, publico: true }); setSucesso(r.mensagem || 'Arquivo enviado com sucesso.'); setArquivo(undefined); } catch (e) { setErro(e instanceof Error ? e.message : 'Falha no envio.'); } finally { setEnviando(false); } }
  if (!info && !erro) return <div className="pagina-publica"><Carregando/></div>; if (!info) return <div className="pagina-publica"><ErroEstado mensagem={erro}/></div>;
  return <main className="pagina-publica"><section className="publico-caixa"><header className="publico-cabecalho" style={{ background: info.cor_primaria }}><h1>{info.titulo}</h1><p>{info.instituicao}</p></header><div className="publico-corpo"><p>{info.descricao}</p><div className="aviso info"><Upload size={20}/><div className="texto">Até {info.tamanho_maximo_mb} MB. Formatos: {info.extensoes_aceitas?.join(', ') || 'formatos permitidos pela instituição'}.</div></div>{sucesso && <div className="aviso sucesso"><ShieldCheck size={20}/>{sucesso}</div>}{erro && <div className="aviso erro">{erro}</div>}<form className="margem-topo" onSubmit={enviar}>{info.exigir_identificacao && <div className="campo"><label>Seu nome</label><input required value={form.nome} onChange={(e) => setForm({...form, nome:e.target.value})}/></div>}{info.exigir_email && <div className="campo"><label>Seu e-mail</label><input type="email" required value={form.email} onChange={(e) => setForm({...form, email:e.target.value})}/></div>}{info.exige_senha && <div className="campo"><label>Senha da solicitação</label><input type="password" required value={form.senha} onChange={(e) => setForm({...form, senha:e.target.value})}/></div>}<div className="campo"><label>Arquivo</label><input type="file" required onChange={(e) => setArquivo(e.target.files?.[0])}/></div><div className="campo"><label>Observação</label><textarea value={form.observacao} onChange={(e) => setForm({...form, observacao:e.target.value})}/></div>{info.termo_responsabilidade && <label className="caixa-marcacao"><input type="checkbox" required/> <span>Li e aceito: {info.termo_responsabilidade}</span></label>}<button className="botao principal" disabled={!arquivo || enviando}><Send size={17}/>{enviando ? 'Enviando…' : 'Enviar documento'}</button></form></div></section></main>;
}

