# renew_before_expiry = 30 days
version = 3.3.0
archive_dir = /etc/letsencrypt/archive/govsistem.com.br
cert = /etc/letsencrypt/live/govsistem.com.br/cert.pem
privkey = /etc/letsencrypt/live/govsistem.com.br/privkey.pem
chain = /etc/letsencrypt/live/govsistem.com.br/chain.pem
fullchain = /etc/letsencrypt/live/govsistem.com.br/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 94880dfb0e25198a74a35e8e552293c0
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
webroot_path = /var/www/certbot,
[[webroot_map]]
doe-admin.govsistem.com.br = /var/www/certbot
