from app.models.acao_coletiva import (
    AcaoColetiva,
    EncontroFrequencia,
    Inscricao,
    RegistroFrequencia,
)
from app.models.acompanhamento import Acompanhamento
from app.models.agenda import Appointment, VisitaDomiciliar
from app.models.attendance import (
    Attendance,
    AttendanceMember,
    AttendanceProfessional,
)
from app.models.audit_trail import AuditTrail
from app.models.autenticador import (
    DocumentoAutenticavel,
    ExportacaoExecucao,
    ExportadorDado,
)
from app.models.base import Base, SoftDeleteMixin, TenantMixin, TimestampMixin
from app.models.beneficio import ConcessaoBeneficio, EstoqueUnidade, LimiteBeneficio
from app.models.case_file import CaseFile
from app.models.case_file_attachment import CaseFileAttachment
from app.models.domain import (
    AccessForm,
    BenefitType,
    ReferralCode,
    ServiceType,
)
from app.models.domicilio import DadosDomicilio
from app.models.domain_tables import (
    AtoInfracional,
    Bairro,
    Cargo,
    Cartorio,
    EquipeAtendimento,
    Escolaridade,
    Especialidade,
    EstadoCivil,
    EstrategiaAtendimento,
    Feriado,
    GrauInstrucao,
    GrupoInsumo,
    Instituicao,
    Logradouro,
    MotivoAcolhimento,
    MotivoCancelamento,
    MotivoEncerramentoAcolhimento,
    MotivoInativacao,
    MotivoInativacaoPrograma,
    MotivoReinsercao,
    NecessidadeEspecial,
    ObjetivoEncaminhamento,
    OrgaoEmissor,
    OrientacaoSexual,
    OrigemEncaminhamento,
    Parentesco,
    Parceria,
    PessoaJuridica,
    PontoEmbarque,
    Potencialidade,
    ProcedimentoRealizado,
    ProgramaSocial,
    RegimeContratacao,
    Religiao,
    TipoAtividadeColetiva,
    UnidadeFederativa,
    UnidadeMedida,
    VulnerabilidadeTipo,
)
from app.models.encaminhamento import Encaminhamento
from app.models.enums import (
    AcaoColetivaTipo,
    AcaoStatus,
    AcompanhamentoSituacao,
    AcompanhamentoTipo,
    AppointmentStatus,
    AppointmentTipo,
    AuditAccessType,
    AuditAction,
    BenefitCategory,
    CaseFileStatus,
    ConcessaoStatus,
    DomainSource,
    EncaminhamentoStatus,
    EncaminhamentoTipo,
    Escolaridade,
    FaixaEtaria,
    FaixaRenda,
    FrequenciaCumprimento,
    MedidaSocioeducativa,
    MembershipStatus,
    MotivoDesligamento,
    Parentesco,
    Periodicidade,
    ProtecaoNivel,
    ReferralArea,
    ResultadoAvaliacao,
    RoleName,
    Sexo,
    StatusAcaoColetiva,
    StatusInscricao,
    StatusRecepcao,
    TipoAtendimento,
    TipoDeficiencia,
    TipoDocumento,
    TipoRelatorioPia,
    UnitType,
    VisitaStatus,
)
from app.models.external_shortcut import ExternalShortcut
from app.models.family import Family
from app.models.habitacional import (
    AtividadeHabitacional,
    DemandaHabitacional,
    DocumentoHabitacional,
    ProgramaHabitacional,
)
from app.models.importacao import ImportJob, ImportLog
from app.models.notificacao import FiltroSalvo, Notificacao
from app.models.organization import Organization
from app.models.person import Person
from app.models.person_family_membership import PersonFamilyMembership
from app.models.pia import Pia, RelatorioPia
from app.models.plano_acompanhamento import (
    AcaoPlano,
    AvaliacaoPlano,
    PlanoAcompanhamento,
)
from app.models.professional import Professional
from app.models.professional_assignment import ProfessionalAssignment
from app.models.questionario import (
    Questao,
    Questionario,
    RespostaQuestao,
    RespostaQuestionario,
)
from app.models.reception_log import ReceptionLog
from app.models.refresh_token import RefreshToken
from app.models.retention import RetentionPolicy
from app.models.rma import RmaAjuste, RmaFechamento
from app.models.role import Role
from app.models.sibec import SibecData
from app.models.sicon import SiconData
from app.models.socioeconomico import (
    CondicoesEducacionais,
    CondicoesSaude,
    ConvivenciaFamiliar,
    DadosRua,
    DespesaFamiliar,
    PotencialidadeFamiliar,
    RendaMembro,
    VulnerabilidadeFamiliar,
)
from app.models.unit import Unit
from app.models.user import User
from app.models.user_role import UserRole

__all__ = [
    "Base",
    "TimestampMixin",
    "SoftDeleteMixin",
    "TenantMixin",
    "AcaoColetiva",
    "AcaoColetivaTipo",
    "AcaoStatus",
    "Acompanhamento",
    "AcompanhamentoSituacao",
    "AcompanhamentoTipo",
    "AcaoPlano",
    "Appointment",
    "AppointmentStatus",
    "AppointmentTipo",
    "AtividadeHabitacional",
    "AuditAccessType",
    "AuditAction",
    "AvaliacaoPlano",
    "BenefitCategory",
    "CaseFileStatus",
    "ConcessaoBeneficio",
    "ConcessaoStatus",
    "CondicoesEducacionais",
    "CondicoesSaude",
    "ConvivenciaFamiliar",
    "DadosRua",
    "DemandaHabitacional",
    "DespesaFamiliar",
    "DocumentoAutenticavel",
    "DocumentoHabitacional",
    "DomainSource",
    "DadosDomicilio",
    "DocumentoAutenticavel",
    "Encaminhamento",
    "EncaminhamentoStatus",
    "EncaminhamentoTipo",
    "EncontroFrequencia",
    "Escolaridade",
    "EstoqueUnidade",
    "ExportacaoExecucao",
    "ExportadorDado",
    "ExternalShortcut",
    "FaixaEtaria",
    "FaixaRenda",
    "FiltroSalvo",
    "FrequenciaCumprimento",
    "ImportJob",
    "ImportLog",
    "Inscricao",
    "LimiteBeneficio",
    "MedidaSocioeducativa",
    "MembershipStatus",
    "MotivoDesligamento",
    "Notificacao",
    "Parentesco",
    "Periodicidade",
    "ProtecaoNivel",
    "ReferralArea",
    "RegistroFrequencia",
    "ResultadoAvaliacao",
    "RetentionPolicy",
    "RmaAjuste",
    "RmaFechamento",
    "RoleName",
    "SibecData",
    "SiconData",
    "Sexo",
    "StatusAcaoColetiva",
    "StatusInscricao",
    "StatusRecepcao",
    "TipoAtendimento",
    "TipoDeficiencia",
    "TipoDocumento",
    "TipoRelatorioPia",
    "UnitType",
    "VisitaDomiciliar",
    "VisitaStatus",
    "Organization",
    "Role",
    "User",
    "UserRole",
    "RefreshToken",
    "Unit",
    "Professional",
    "ProfessionalAssignment",
    "AccessForm",
    "BenefitType",
    "ReferralCode",
    "ServiceType",
    "AuditTrail",
    "Family",
    "Person",
    "PersonFamilyMembership",
    "CaseFile",
    "Attendance",
    "AttendanceMember",
    "AttendanceProfessional",
    "ReceptionLog",
    "CaseFileAttachment",
    "PlanoAcompanhamento",
    "Pia",
    "PotencialidadeFamiliar",
    "ProgramaHabitacional",
    "Questao",
    "Questionario",
    "RelatorioPia",
    "RendaMembro",
    "RespostaQuestao",
    "RespostaQuestionario",
    "VulnerabilidadeFamiliar",
]
