from enum import Enum


class TipoOrganizacao(str, Enum):
    PUBLICO = "PUBLICO"
    PRIVADO = "PRIVADO"


class TipoVeiculo(str, Enum):
    CARRO = "CARRO"
    UTILITARIO = "UTILITARIO"
    CAMINHONETE = "CAMINHONETE"
    CAMINHAO = "CAMINHAO"
    ONIBUS = "ONIBUS"
    MICRO_ONIBUS = "MICRO_ONIBUS"
    VAN = "VAN"
    MOTOCICLETA = "MOTOCICLETA"
    MAQUINA = "MAQUINA"
    TRATOR = "TRATOR"
    EQUIPAMENTO = "EQUIPAMENTO"
    OUTRO = "OUTRO"


class SituacaoVeiculo(str, Enum):
    DISPONIVEL = "DISPONIVEL"
    EM_USO = "EM_USO"
    EM_MANUTENCAO = "EM_MANUTENCAO"
    INDISPONIVEL = "INDISPONIVEL"
    BAIXADO = "BAIXADO"


class CategoriaFornecedor(str, Enum):
    COMBUSTIVEL = "COMBUSTIVEL"
    AUTOPECAS = "AUTOPECAS"
    PNEUS = "PNEUS"
    ELETRICA = "ELETRICA"
    MECANICA = "MECANICA"
    FUNILARIA = "FUNILARIA"
    CONCESSIONARIA = "CONCESSIONARIA"
    OUTRO = "OUTRO"


class TipoMovimentacao(str, Enum):
    ENTRADA = "ENTRADA"
    SAIDA = "SAIDA"
    AJUSTE_POSITIVO = "AJUSTE_POSITIVO"
    AJUSTE_NEGATIVO = "AJUSTE_NEGATIVO"
    TRANSFERENCIA_ENTRADA = "TRANSFERENCIA_ENTRADA"
    TRANSFERENCIA_SAIDA = "TRANSFERENCIA_SAIDA"
    ESTORNO = "ESTORNO"


class OrigemMovimentacao(str, Enum):
    ENTRADA_COMPRA = "ENTRADA_COMPRA"
    ABASTECIMENTO = "ABASTECIMENTO"
    AJUSTE_MANUAL = "AJUSTE_MANUAL"
    INVENTARIO = "INVENTARIO"
    TRANSFERENCIA = "TRANSFERENCIA"
    ESTORNO_ABASTECIMENTO = "ESTORNO_ABASTECIMENTO"
    CANCELAMENTO_ENTRADA = "CANCELAMENTO_ENTRADA"


class StatusAbastecimento(str, Enum):
    CONFIRMADO = "CONFIRMADO"
    CANCELADO = "CANCELADO"


class PrioridadeManutencao(str, Enum):
    BAIXA = "BAIXA"
    NORMAL = "NORMAL"
    ALTA = "ALTA"
    URGENTE = "URGENTE"


class StatusManutencao(str, Enum):
    ABERTA = "ABERTA"
    AGUARDANDO_ORCAMENTO = "AGUARDANDO_ORCAMENTO"
    APROVADA = "APROVADA"
    EM_MANUTENCAO = "EM_MANUTENCAO"
    CONCLUIDA = "CONCLUIDA"
    CANCELADA = "CANCELADA"


class GravidadeOcorrencia(str, Enum):
    BAIXA = "BAIXA"
    MEDIA = "MEDIA"
    ALTA = "ALTA"
    CRITICA = "CRITICA"


class StatusOcorrencia(str, Enum):
    ABERTA = "ABERTA"
    EM_ANALISE = "EM_ANALISE"
    RESOLVIDA = "RESOLVIDA"
    CONVERTIDA_EM_MANUTENCAO = "CONVERTIDA_EM_MANUTENCAO"


class BasePreventiva(str, Enum):
    QUILOMETRAGEM = "QUILOMETRAGEM"
    HORIMETRO = "HORIMETRO"
    DATA = "DATA"
    MESES = "MESES"
