"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Columns3, List, Network, Search } from "lucide-react";
import { api } from "@/lib/api";
import type { DemandaV2 } from "@/types/govtask";
import { formatDate } from "@/lib/utils";

type Modo = "kanban" | "lista" | "agenda" | "dependencias";
export default function OperacaoPage() {
 const [itens,setItens]=useState<DemandaV2[]>([]); const [modo,setModo]=useState<Modo>("kanban"); const [q,setQ]=useState("");
 useEffect(()=>{api.listDemandasV2({q}).then(x=>setItens(x.items));},[q]);
 const grupos=useMemo(()=>{const g:Record<string,DemandaV2[]>={"Abertas":[],"Em andamento":[],"Aguardando":[],"Concluídas":[]};itens.forEach(d=>{const s=(d.status?.rotulo||"").toLowerCase();g[s.includes("concl")?"Concluídas":s.includes("aguard")?"Aguardando":d.progresso>0?"Em andamento":"Abertas"].push(d)});return g},[itens]);
 const botoes:[Modo,string,any][]=[["kanban","Kanban",Columns3],["lista","Lista",List],["agenda","Agenda",CalendarDays],["dependencias","Dependências",Network]];
 return <div className="max-w-7xl space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-700">Controle de fluxo</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Mesa operacional</h1><p className="mt-1 text-sm text-slate-600">A mesma demanda vista pelo estágio, prazo ou relação de dependência.</p></header><div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-3 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-lg bg-slate-50 px-3"><Search className="h-4 w-4 text-slate-400"/><input className="h-9 w-full bg-transparent text-sm outline-none" value={q} onChange={e=>setQ(e.target.value)} placeholder="Filtrar demandas"/></label><div className="flex gap-1 overflow-auto">{botoes.map(([key,label,Icon])=><button key={key} onClick={()=>setModo(key)} className={`flex items-center gap-2 whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold ${modo===key?'bg-slate-900 text-white':'text-slate-600 hover:bg-slate-100'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div></div>
 {modo==="kanban"&&<div className="grid gap-4 lg:grid-cols-4">{Object.entries(grupos).map(([nome,ds])=><section key={nome} className="min-h-64 rounded-xl bg-slate-100 p-3"><div className="mb-3 flex justify-between px-1"><h2 className="text-sm font-bold text-slate-700">{nome}</h2><span className="text-xs text-slate-500">{ds.length}</span></div><div className="space-y-3">{ds.map(d=><Card key={d.id} d={d}/>)}</div></section>)}</div>}
 {modo==="lista"&&<section className="overflow-hidden rounded-xl border border-slate-200 bg-white divide-y divide-slate-100">{itens.map(d=><Card key={d.id} d={d} linha/>)}</section>}
 {modo==="agenda"&&<section className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{itens.filter(d=>d.prazo_final).sort((a,b)=>(a.prazo_final||"").localeCompare(b.prazo_final||"")).map(d=><Card key={d.id} d={d}/>)}</section>}
 {modo==="dependencias"&&<section className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-bold text-slate-900">Mapa de dependências</h2><p className="mt-1 text-sm text-slate-600">Abra uma demanda para visualizar tarefas, subtarefas e bloqueios. As ligações são mantidas na tarefa para não esconder a causa real de uma espera.</p><div className="mt-6 space-y-3">{itens.slice(0,12).map((d,i)=><Link className="flex items-center gap-3 rounded-lg border border-slate-200 p-4 hover:border-blue-400" key={d.id} href={`/demandas/${d.id}`}><span className="grid h-7 w-7 place-items-center rounded-full bg-blue-100 text-xs font-bold text-blue-700">{i+1}</span><div><p className="font-semibold text-slate-800">{d.titulo}</p><p className="text-xs text-slate-500">{d.proxima_acao||"Sem próxima ação"}</p></div></Link>)}</div></section>}
 </div>;
}
function Card({d,linha}:{d:DemandaV2;linha?:boolean}){return <Link href={`/demandas/${d.id}`} className={`block rounded-lg border border-slate-200 bg-white p-4 shadow-sm transition hover:border-blue-400 hover:shadow ${linha?'rounded-none border-x-0 border-t-0 shadow-none':''}`}><div className="flex justify-between gap-2"><span className="font-mono text-[11px] text-slate-500">{d.numero}</span>{d.atrasada&&<span className="text-[11px] font-bold text-red-700">ATRASADA</span>}</div><p className="mt-2 font-semibold text-sm text-slate-800">{d.titulo}</p><p className="mt-2 text-xs text-slate-500">{d.setor_atual?.nome||"Sem setor"} · {d.progresso}%</p>{d.prazo_final&&<p className="mt-2 text-xs text-slate-600">Prazo: {formatDate(d.prazo_final)}</p>}</Link>}
