"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Filter, Plus, Search, AlertTriangle, Clock3, X } from "lucide-react";
import { api } from "@/lib/api";
import { formatDate } from "@/lib/utils";
import type { DemandaV2, DemandaV2Page } from "@/types/govtask";

export default function DemandasPage() {
  const [dados, setDados] = useState<DemandaV2Page>(); const [q, setQ] = useState("");
  const [filtro, setFiltro] = useState<"todas"|"atrasadas"|"minhas"|"externo">("todas"); const [nova, setNova] = useState(false); const [titulo, setTitulo] = useState("");
  const carregar = useCallback(async () => setDados(await api.listDemandasV2({ q, atrasadas: filtro === "atrasadas", minhas: filtro === "minhas", aguardando_externo: filtro === "externo" })), [q, filtro]);
  useEffect(() => { const timer = setTimeout(() => carregar(), 180); return () => clearTimeout(timer); }, [carregar]);
  async function criar(e: FormEvent) { e.preventDefault(); if (!titulo.trim()) return; const d = await api.criarDemandaV2({ titulo }); setNova(false); setTitulo(""); window.location.href = `/demandas/${d.id}`; }
  return <div className="max-w-7xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-blue-700">Dossiês municipais</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Demandas</h1><p className="mt-1 text-sm text-slate-600">Cada determinação acompanhada até a entrega final.</p></div><button onClick={() => setNova(true)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-800"><Plus className="h-4 w-4"/>Nova demanda</button></header>
    <section className="rounded-xl border border-slate-200 bg-white p-3"><div className="flex flex-col gap-3 lg:flex-row"><label className="flex flex-1 items-center gap-2 rounded-lg bg-slate-50 px-3"><Search className="h-4 w-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por número, título, objeto ou assunto" className="h-10 w-full bg-transparent text-sm outline-none"/></label><div className="flex gap-2 overflow-auto">{([['todas','Todas'],['minhas','Sob minha gestão'],['atrasadas','Atrasadas'],['externo','Aguardando externo']] as const).map(([key,label])=><button key={key} onClick={()=>setFiltro(key)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold ${filtro===key?'bg-slate-900 text-white':'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{label}</button>)}</div></div></section>
    <p className="text-sm text-slate-500">{dados ? `${dados.total} demanda(s) encontrada(s)` : "Carregando demandas…"}</p><section className="overflow-hidden rounded-xl border border-slate-200 bg-white divide-y divide-slate-100">{dados?.items.map(d=><DemandaLinha key={d.id} d={d}/>) || <div className="p-12 text-center text-sm text-slate-500">Carregando…</div>}{dados?.items.length === 0 && <div className="p-12 text-center text-sm text-slate-500">Nenhuma demanda neste recorte.</div>}</section>
    {nova && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={criar} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-lg font-bold">Nova demanda</h2><p className="mt-1 text-sm text-slate-500">Comece pelo que foi solicitado; os detalhes podem ser registrados depois.</p></div><button type="button" onClick={()=>setNova(false)}><X className="h-5 w-5"/></button></div><input autoFocus value={titulo} onChange={e=>setTitulo(e.target.value)} className="mt-5 w-full rounded-lg border border-slate-300 px-3 py-3 text-sm" placeholder="Ex.: Aquisição de ambulância"/><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setNova(false)} className="rounded-lg px-4 py-2 text-sm">Cancelar</button><button className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Criar demanda</button></div></form></div>}
  </div>;
}
function DemandaLinha({d}:{d:DemandaV2}) { return <Link href={`/demandas/${d.id}`} className="group flex flex-col gap-3 p-5 hover:bg-slate-50 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex gap-2"><span className="font-mono text-xs text-slate-500">{d.numero}</span>{d.atrasada&&<span className="text-xs font-semibold text-red-700">Atrasada</span>}</div><p className="mt-1 truncate font-semibold text-slate-900 group-hover:text-blue-700">{d.titulo}</p><p className="mt-1 text-xs text-slate-500">{d.setor_atual?.nome || "Sem setor"} · {d.responsavel_geral?.name || "Sem responsável"}</p></div><div className="flex items-center gap-5"><div className="hidden w-28 sm:block"><div className="h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-blue-600" style={{width:`${d.progresso}%`}}/></div><p className="mt-1 text-xs text-slate-500">{d.progresso}% concluído</p></div><div className="min-w-28 text-right"><p className="text-sm font-medium text-slate-700">{d.status?.rotulo || "Aberta"}</p><p className={`mt-1 text-xs ${d.atrasada?'text-red-700':'text-slate-500'}`}>{d.prazo_final ? `Prazo: ${formatDate(d.prazo_final)}` : "Sem prazo"}</p></div></div></Link> }
