import type { Config } from "tailwindcss";
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        primary: { 50: "#eff6ff", 100: "#dbeafe", 200: "#bfdbfe", 300: "#93c5fd", 400: "#60a5fa", 500: "#3b82f6", 600: "#2563eb", 700: "#1d4ed8", 800: "#1e40af", 900: "#1e3a8a" },
        "on-surface-variant": "#43474f",
        "on-tertiary-container": "#5392ef",
        "on-secondary": "#ffffff",
        outline: "#73777f",
        "on-primary-fixed": "#001c3a",
        "surface-tint": "#40608b",
        "primary-container": "#002b54",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed-variant": "#00468c",
        "inverse-primary": "#a8c8fa",
        "primary-fixed": "#d4e3ff",
        "tertiary-fixed-dim": "#a9c7ff",
        "outline-variant": "#c3c6d0",
        "secondary-container": "#8cf5b1",
        surface: "#f7f9fb",
        "on-primary-fixed-variant": "#264872",
        "secondary-fixed": "#8ff8b4",
        "on-tertiary-fixed": "#001b3d",
        "primary-fixed-dim": "#a8c8fa",
        "surface-bright": "#f7f9fb",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        secondary: "#006d3d",
        "on-primary-container": "#7493c2",
        error: "#ba1a1a",
        background: "#f7f9fb",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#007240",
        tertiary: "#001633",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#73db9a",
        "on-secondary-fixed": "#00210f",
        "tertiary-fixed": "#d6e3ff",
        "tertiary-container": "#002a58",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#00522d",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e8ea",
        sidebar: { DEFAULT: "#0f172a", hover: "#1e293b", active: "#1e3a8a" },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-md": "1.5rem",
        gutter: "1.5rem",
        "stack-sm": "0.5rem",
        "stack-lg": "3rem",
        "margin-mobile": "1rem",
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;
