"""add_closed_status_and_edition_type

Revision ID: 258eddc9cfcd
Revises: 4d53c4d5d567
Create Date: 2026-05-15 16:27:36.903011
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '258eddc9cfcd'
down_revision: Union[str, None] = '4d53c4d5d567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('type', sa.String(length=20), nullable=False))
    op.create_unique_constraint('uq_edition_year_number_type', 'editions', ['year', 'number', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_edition_year_number_type', 'editions', type_='unique')
    op.drop_column('editions', 'type')
    # ### end Alembic commands ###
