"""add_content_json_plain_text_to_matters

Revision ID: 4d53c4d5d567
Revises: 25818ce35b4c
Create Date: 2026-05-15 16:09:59.799038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d53c4d5d567'
down_revision: Union[str, None] = '25818ce35b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matters', sa.Column('content_json', sa.JSON(), nullable=True, comment='Structured editor JSON (e.g. TipTap/ProseMirror)'))
    op.add_column('matters', sa.Column('plain_text', sa.Text(), nullable=False, comment='Plain text extracted from content_html for search'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matters', 'plain_text')
    op.drop_column('matters', 'content_json')
    # ### end Alembic commands ###
