"""fks_use_alter

Revision ID: 423b8eacccf0
Revises: 8acfc1230b44
Create Date: 2026-08-10 20:05:19.575568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '423b8eacccf0'
down_revision: Union[str, None] = '8acfc1230b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'govcompras_aditivos', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_aditivos', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_adjudicacoes', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_adjudicacoes', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_apostilamentos', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_apostilamentos', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_ata_solicitacoes_consumo', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_ata_solicitacoes_consumo', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_atas', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_atas', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_catalogo_itens', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_catalogo_itens', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_contratos', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_contratos', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_cotacoes', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_cotacoes', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_dfds', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_dfds', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_documentos', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_documentos', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_editais', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_editais', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_edital_templates', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_edital_templates', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_etps', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_etps', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_fornecedores', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_fornecedores', 'govcompras_users', ['deleted_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_fornecedores', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_matrizes_risco', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_matrizes_risco', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_medicoes', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_medicoes', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_notas_fiscais', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_notas_fiscais', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_ocorrencias', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_ocorrencias', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_organizacoes', 'govcompras_users', ['deleted_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_processos', 'govcompras_contratos', ['origem_contrato_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_processos', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_processos', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_publicacoes', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_publicacoes', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_secretarias', 'govcompras_users', ['deleted_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_sessoes', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_sessoes', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_setores', 'govcompras_users', ['deleted_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_solicitacoes', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_solicitacoes', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_termos_referencia', 'govcompras_users', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_termos_referencia', 'govcompras_users', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'govcompras_users', 'govcompras_organizacoes', ['organizacao_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'govcompras_users', 'govcompras_users', ['deleted_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'govcompras_users', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_users', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_termos_referencia', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_termos_referencia', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_solicitacoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_solicitacoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_setores', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_sessoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_sessoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_secretarias', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_publicacoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_publicacoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_processos', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_processos', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_processos', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_organizacoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_ocorrencias', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_ocorrencias', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_notas_fiscais', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_notas_fiscais', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_medicoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_medicoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_matrizes_risco', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_matrizes_risco', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_fornecedores', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_fornecedores', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_fornecedores', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_etps', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_etps', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_edital_templates', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_edital_templates', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_editais', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_editais', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_documentos', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_documentos', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_dfds', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_dfds', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_cotacoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_cotacoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_contratos', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_contratos', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_catalogo_itens', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_catalogo_itens', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_atas', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_atas', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_ata_solicitacoes_consumo', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_ata_solicitacoes_consumo', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_apostilamentos', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_apostilamentos', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_adjudicacoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_adjudicacoes', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_aditivos', type_='foreignkey')
    op.drop_constraint(None, 'govcompras_aditivos', type_='foreignkey')
    # ### end Alembic commands ###
