"""add_mfa_password_lockout_fields

Revision ID: b8f07e6285f7
Revises: 369d85f8d441
Create Date: 2026-05-15 17:21:02.313674
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8f07e6285f7'
down_revision: Union[str, None] = '369d85f8d441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_secret', sa.Text(), nullable=True, comment='Encrypted TOTP secret'))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_failures', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'password_failures')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    # ### end Alembic commands ###
