import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
    "./.storybook/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        paper: "var(--ga-paper)",
        surface: "var(--ga-surface)",
        "surface-dim": "var(--ga-surface-dim)",
        "surface-container": "var(--ga-surface-container)",
        "surface-container-low": "var(--ga-surface-container-low)",
        "surface-container-lowest": "var(--ga-surface-container-lowest)",
        "surface-container-high": "var(--ga-surface-container-high)",
        "surface-container-highest": "var(--ga-surface-container-highest)",
        "surface-bright": "var(--ga-surface-bright)",
        "surface-variant": "var(--ga-surface-variant)",
        "surface-tint": "var(--ga-surface-tint)",
        ink: "var(--ga-ink)",
        "ink-soft": "var(--ga-ink-soft)",
        primary: "var(--ga-primary)",
        "primary-soft": "var(--ga-primary-soft)",
        "primary-container": "var(--ga-primary-container)",
        "primary-fixed": "var(--ga-primary-fixed)",
        "primary-fixed-dim": "var(--ga-primary-fixed-dim)",
        "on-primary": "var(--ga-on-primary)",
        "on-primary-container": "var(--ga-on-primary-container)",
        "on-primary-fixed": "var(--ga-on-primary-fixed)",
        "on-primary-fixed-variant": "var(--ga-on-primary-fixed-variant)",
        "inverse-primary": "var(--ga-inverse-primary)",
        secondary: "var(--ga-secondary)",
        "secondary-container": "var(--ga-secondary-container)",
        "secondary-fixed": "var(--ga-secondary-fixed)",
        "secondary-fixed-dim": "var(--ga-secondary-fixed-dim)",
        "on-secondary": "var(--ga-on-secondary)",
        "on-secondary-container": "var(--ga-on-secondary-container)",
        "on-secondary-fixed": "var(--ga-on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--ga-on-secondary-fixed-variant)",
        tertiary: "var(--ga-tertiary)",
        "tertiary-container": "var(--ga-tertiary-container)",
        "tertiary-fixed": "var(--ga-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--ga-tertiary-fixed-dim)",
        "on-tertiary": "var(--ga-on-tertiary)",
        "on-tertiary-container": "var(--ga-on-tertiary-container)",
        "on-tertiary-fixed": "var(--ga-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--ga-on-tertiary-fixed-variant)",
        "on-surface": "var(--ga-on-surface)",
        "on-surface-variant": "var(--ga-on-surface-variant)",
        "on-background": "var(--ga-on-background)",
        outline: "var(--ga-outline)",
        "outline-variant": "var(--ga-outline-variant)",
        "inverse-surface": "var(--ga-inverse-surface)",
        "inverse-on-surface": "var(--ga-inverse-on-surface)",
        error: "var(--ga-error)",
        "error-container": "var(--ga-error-container)",
        "on-error": "var(--ga-on-error)",
        amber: "var(--ga-amber)",
        danger: "var(--ga-danger)",
        sensitive: "var(--ga-sensitive)",
        focus: "var(--ga-focus)",
        "evt-paif": "var(--ga-primary)",
        "evt-scfv": "#3E8E7E",
        "evt-paefi": "var(--ga-sensitive)",
        "evt-mse": "var(--ga-amber)",
        "evt-beneficio": "#0B5563",
        "evt-encaminhamento": "#46626B",
        "evt-visita": "#7A5230",
      },
      fontFamily: {
        titulo: ["Hanken Grotesk", "system-ui", "sans-serif"],
        corpo: ["Hanken Grotesk", "system-ui", "sans-serif"],
        mono: ["'IBM Plex Mono'", "ui-monospace", "monospace"],
      },
      fontSize: {
        "headline-xl": ["42px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "700" }],
        "title-md": ["22px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.01em" }],
        xs: ["12px", "1.5"],
        sm: ["14px", "1.5"],
        base: ["16px", "1.5"],
        lg: ["20px", "1.4"],
        xl: ["24px", "1.3"],
        "2xl": ["32px", "1.2"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.75rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        full: "9999px",
        cartao: "12px",
        input: "10px",
      },
      boxShadow: {
        um: "0 4px 6px -1px rgba(0,0,0,0.02), 0 10px 15px -3px rgba(0,0,0,0.03)",
        premium: "0 10px 30px -10px rgba(0,0,0,0.04)",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        gutter: "32px",
        lg: "48px",
        xl: "80px",
        "margin-desktop": "48px",
        "margin-mobile": "20px",
        toque: "48px",
      },
    },
  },
  plugins: [],
};

export default config;
